"""Generate/check the paper's offline evidence, tables and search figure."""

import argparse
import csv
import importlib.metadata
import io
import json
import os
from pathlib import Path
import sys
import tempfile

sys.dont_write_bytecode = True
from ara_v1_data import (  # noqa: E402
    DEFAULT_SOURCE, REPO_ROOT, InputError, load_summary, parse_json, sha256,
)

DEFAULT_PAPER = REPO_ROOT / "docs/papers/heretic-ara"
CSV_FIELDS = (
    "trial_number,display_index,state,keywords,keyword_count,sample_count,kl,"
    "baseline_keywords,baseline_kl,absolute_drop,relative_drop,"
    "numerical_gate_pass,pareto,phase,start_layer_index,end_layer_index,"
    "attn_strength,mlp_strength,mlp_strength_raw,push_weight,margin,"
    "layer_start_fraction,layer_span_fraction,terminal_line,score_lines"
).split(",")
TEXT_OUTPUTS = (
    "evidence/ara-v1-summary.json", "evidence/ara-v1-trials.csv",
    "tables/ara-protocol.tex", "tables/ara-v1-results.tex",
    "tables/ara-v1-distribution.tex",
)
FIGURE_OUTPUTS = ("figures/ara-v1-search.pdf", "figures/ara-v1-search.png")
MANIFEST = "evidence/figure-manifest.json"
PLOT_CONFIG = {
    "figure_inches": [8.2, 4.8], "dpi": 200,
    "xlim": [0, 0.16], "ylim": [0, 1.02],
    "xlabel": "First-token KL divergence (nats)",
    "ylabel": "Refusal-keyword rate",
    "phase_labels": ["Trials 0-35", "Trials 36-79", "Trials 80-119"],
    "phase_colors": ["#416FAD", "#D88935", "#58A092"],
    "phase_names": ["startup", "search-36-79", "search-80-119"],
    "gate_kl": 0.15, "gate_keywords": 0.10,
    "annotated_trials": [40, 66, 119],
    "annotation_offsets": [[105, -27], [12, 16], [15, -25]],
    "font_family": "DejaVu Sans", "font_size": 10,
    "scatter_size": 27, "pareto_size": 75, "pareto_marker": "o",
    "pareto_color": "#20242B", "gate_color": "#A33B3B",
    "scatter_alpha": 0.78, "grid_alpha": 0.2,
    "legend_location": "center right", "layout": "constrained",
}


class OutputError(ValueError):
    """Derived evidence is stale, invalid, or cannot be safely written."""


def json_bytes(value):
    """Serialize deterministic UTF-8 JSON with finite values and final LF."""
    return (json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False)
            + "\n").encode("utf-8")


def validate_paths(source, paper_dir):
    """Resolve input/output paths before any write.

    Args:
        source: Archive directory, relative to caller cwd when not absolute.
        paper_dir: Destination directory within the workspace.
    Returns:
        Resolved input and output Path objects.
    Raises:
        InputError: Paths overlap, escape or resolve through an unsafe symlink.
    """
    source, paper = Path(source).resolve(), Path(paper_dir).resolve()
    if not paper.is_relative_to(REPO_ROOT):
        raise InputError(f"paper directory outside workspace: {paper}")
    if not source.is_relative_to(REPO_ROOT):
        raise InputError(f"source directory outside workspace: {source}")
    if paper.is_relative_to(source) or source.is_relative_to(paper):
        raise InputError("source/paper directories overlap")
    for name in (*TEXT_OUTPUTS, *FIGURE_OUTPUTS, MANIFEST, "build"):
        target = (paper / name).resolve()
        if not target.is_relative_to(paper):
            raise InputError(f"output symlink escapes paper directory: {name}")
        if target.is_relative_to(source) or source.is_relative_to(target):
            raise InputError(f"output overlaps archive: {name}")
    return source, paper


def _csv_row(trial):
    row = {field: trial.get(field) for field in CSV_FIELDS}
    resolved, raw = trial["resolved_params"], trial["raw_params"]
    for field in ("start_layer_index", "end_layer_index"):
        row[field] = resolved[field]
    row["attn_strength"] = resolved["components"]["attn.o_proj"]["strength"]
    row["mlp_strength"] = resolved["components"]["mlp.down_proj"]["strength"]
    for field in ("mlp_strength_raw", "push_weight", "margin",
                  "layer_start_fraction", "layer_span_fraction"):
        row[field] = raw[f"ara.{field}"]
    row["score_lines"] = ";".join(map(str, trial["score_lines"]))
    for field, value in row.items():
        if isinstance(value, bool):
            row[field] = str(value).lower()
    return row


def render_csv(summary):
    """Render the fixed-order trial CSV, preserving raw precision.

    Args:
        summary: A validated RunSummary from load_summary.
    Returns:
        UTF-8 CSV bytes with LF line endings.
    """
    buffer = io.StringIO(newline="")
    writer = csv.DictWriter(buffer, CSV_FIELDS, lineterminator="\n")
    writer.writeheader()
    writer.writerows(_csv_row(trial) for trial in summary["trials"])
    return buffer.getvalue().encode("utf-8")


def _table(caption, label, columns, rows, note=""):
    return "\n".join([
        "% Generated by summarize_ara_v1.py; do not edit.",
        r"\begin{table}[tbp]", r"\centering", r"\small",
        "\\caption{" + caption + "}", "\\label{" + label + "}",
        "\\begin{tabularx}{\\linewidth}{" + columns + "}",
        r"\toprule", *rows, r"\bottomrule", r"\end{tabularx}",
        r"\par\vspace{3pt}", r"\begin{minipage}{\linewidth}\footnotesize",
        note, r"\end{minipage}", r"\end{table}", "",
    ])


def _format_keywords(count, denominator):
    return f"{count}/{denominator}（{100 * count / denominator:.0f}\\%）"


def render_results(summary):
    """Render the baseline, validation candidates and explicit missing rows.

    Args:
        summary: A validated RunSummary from load_summary.
    Returns:
        UTF-8 LaTeX table bytes, with fixed display precision.
    """
    baseline, count = summary["baseline"], summary["baseline"]["sample_count"]
    base_display = _format_keywords(round(baseline["keywords"] * count), count)
    rows = [r"对象 & Keywords & 首 token KL & 证据定位 \\", r"\midrule",
            f"未修改基座 & {base_display} & 0（定义） & 同次运行基线" + r" \\",
            r"Heretic 方向消融 & — & — & 无同协议归档结果 \\"]
    selected = [(summary["best_keyword_trial"], "最低 Keywords"),
                (summary["last_trial"], "最后候选"),
                (summary["min_kl_trial"], "最低 KL")]
    for number, meaning in selected:
        trial = summary["trials"][number]
        keywords = _format_keywords(
            trial["keyword_count"], trial["sample_count"],
        )
        rows.append(f"ARA point-v1，{number} & {keywords} & {trial['kl']:.6f} & "
                    + meaning + r"；未通过验收 \\")
    rows.append(r"ARA trajectory-v2 & — & — & 当前代码适配；无本归档实测 \\")
    note = ("注：基座不是 Heretic 干预结果；“—”表示无数据。编号为从 0 起始的 "
            "trial number；trial 66 来自反复使用的验证集，不是独立测试最优或已导出模型。")
    return _table("同次基座与 ARA 验证候选结果", "tab:results",
                  "@{}lrrX@{}", rows, note).encode("utf-8")


def render_distribution(summary):
    """Render candidate quantiles, threshold counts, Pareto and phase stats.

    Args:
        summary: A validated RunSummary from load_summary.
    Returns:
        UTF-8 LaTeX table bytes, with two tabular blocks in one float.
    """
    quantiles, trials = summary["quantiles"], summary["trials"]
    keywords = " & ".join(f"{value:.2f}" for value in quantiles["keywords"])
    kl = " & ".join(f"{value:.6f}" for value in quantiles["kl"])
    rows = [r"指标 & 最小 & 25\% & 中位数 & 75\% & 最大 \\",
            r"\midrule", "Keywords & " + keywords + r" \\",
            "KL & " + kl + r" \\", r"\midrule"]
    gate, total = summary["gate_thresholds"], summary["trial_count"]
    counts = [("COMPLETE", summary["state_counts"]["COMPLETE"]),
              (r"Keywords $\leq 0.10$",
               sum(t["keywords"] <= gate["keyword_max"] for t in trials)),
              (r"KL $\leq 0.15$",
               sum(t["kl"] <= gate["kl_max"] for t in trials)),
              ("数值联合通过", summary["numerical_gate_count"])]
    for name, value in counts:
        rows.append(f"\\multicolumn{{3}}{{l}}{{{name}}} & "
                    + f"\\multicolumn{{3}}{{r}}{{{value}/{total}}}" + r" \\")
    rows.append(r"\multicolumn{3}{l}{Pareto 候选数} & "
                + "\\multicolumn{3}{r}{"
                + str(len(summary["pareto_trial_numbers"])) + r"} \\")
    text = _table("120 个验证候选的搜索分布", "tab:distribution",
                  "@{}lXXXXX@{}", rows,
                  "注：分位数采用线性插值；数值门槛不代替完整 acceptance。"
                  "这些统计描述同次搜索的候选分布，不构成独立重复实验。")
    phase_rows = [r"trial 区间 & 候选数 & 最低 Keywords & 中位数 & 均值 \\",
                  r"\midrule"]
    for phase in summary["phase_statistics"]:
        phase_rows.append(
            f"{phase['first_trial']}--{phase['last_trial']} & "
            f"{phase['count']} & "
            f"{phase['minimum']:.3f} & {phase['median']:.3f} & "
            f"{phase['mean']:.3f}" + r" \\",
        )
    # Both tabular blocks share a single caption and float identity.
    phase_text = "\n".join([r"\par\vspace{8pt}",
        r"\begin{tabularx}{\linewidth}{@{}lrrrr@{}}", r"\toprule",
        *phase_rows, r"\bottomrule", r"\end{tabularx}", ""])
    return text.replace(r"\end{table}", phase_text + r"\end{table}").encode()


def render_protocol(summary):
    """Render point-v1 archive versus current v2 template settings.

    Args:
        summary: Validated RunSummary including the current v2 template.
    Returns:
        UTF-8 LaTeX protocol table bytes.
    """
    first, second = summary["effective_settings"], summary["v2_template"]
    first_split = first["scorer"]["KeywordRate"]["prompts"]["split"]
    second_split = second["scorer"]["KeywordRate"]["prompts"]["split"]
    anchors = len(second["ara_seed_trials"])
    random = second["n_startup_trials"]
    tpe = second["n_trials"] - anchors - random
    protocol = [
        ("模型 revision", "未固定", "模板固定；本归档无测量"),
        ("精度／量化", "BF16／none", "BF16／none"),
        ("LoRA 秩上界", str(first["ara_lora_rank"]),
         str(second["ara_lora_rank"])),
        ("校准规模（每类）", str(first["ara_calibration_size"]),
         str(second["ara_calibration_size"])),
        ("采集位置／批量", "单个预测位置／1",
         f"至多 {second['ara_trajectory_tokens']} 个预测位置／1"),
        ("验证切分（每类）", first_split, second_split),
        ("独立 audit", "配置 test[:100]；无分数", "锁定后新进程一次消费"),
        ("生成", "seed 42，greedy，最多 100 token", "同左（模板）"),
        ("评估 batch size", f"自动 0，实际 {first['batch_size']}",
         str(second["batch_size"])),
        ("搜索维度", "6；MLP 负 strength 截断至 0",
         f"{len(second['ara_search_space'])}；另有两类 deployment gain"),
        ("搜索预算", f"startup {first['n_startup_trials']} + "
         f"后续 {first['n_trials'] - first['n_startup_trials']}",
         f"anchors {anchors} + random {random} + TPE {tpe}"),
        ("优化指标", "Keywords、首 token KL", "Refusal log-odds、首 token KL"),
        ("关键词集合", "显式增加 9 个中文 markers", "未覆盖；沿用源码默认值"),
        ("增量检查", "数值规范化与候选 gate",
         f"good delta 比率 $\\leq {second['ara_max_good_delta_rms']:.2f}$；"
         f"最大奇异值 $\\leq {second['ara_max_singular_value']:.1f}$"),
        ("结果状态", "120 个候选完成；验收失败", "实现／模板；无本归档实测"),
    ]
    rows = [r"项目 & point-v1 本次实测 & trajectory-v2 当前模板 \\",
            r"\midrule", *(" & ".join(row) + r" \\" for row in protocol)]
    return _table("point-v1 归档协议与 trajectory-v2 模板", "tab:protocol",
                  "@{}p{27mm}XX@{}", rows,
                  "注：模板参数不代表已经执行；验证切分、markers 和目标不同，"
                  "不能直接横比效果。采集 batch 与评估 batch 分开记录。"
                  ).encode("utf-8")


def render_outputs(summary):
    """Render all deterministic text artifacts.

    Args:
        summary: A validated RunSummary from load_summary.
    Returns:
        A map from paper-relative paths to UTF-8 artifact bytes.
    """
    return dict(zip(TEXT_OUTPUTS, (
        json_bytes(summary), render_csv(summary), render_protocol(summary),
        render_results(summary), render_distribution(summary),
    ), strict=True))


def _figure_inputs(paper_dir, rendered):
    inputs = {(paper_dir / name).relative_to(REPO_ROOT).as_posix(): sha256(
        rendered[name]) for name in TEXT_OUTPUTS[:2]}
    for name in ("ara_v1_data.py", "summarize_ara_v1.py"):
        path = Path(__file__).resolve().parent / name
        relative = path.relative_to(REPO_ROOT).as_posix()
        inputs[relative] = sha256(path.read_bytes())
    return inputs


def _figure_manifest(paper_dir, rendered, artifacts):
    return {
        "schema_version": "heretic-ara-figures-v1",
        "input_hashes": _figure_inputs(paper_dir, rendered),
        "plot_config": PLOT_CONFIG,
        "tool_versions": {
            "matplotlib": importlib.metadata.version("matplotlib"),
        },
        "artifact_hashes": {
            (paper_dir / name).relative_to(REPO_ROOT).as_posix():
            sha256(payload)
            for name, payload in artifacts.items()
        },
    }


def _plot_candidates(axis, trials):
    config = PLOT_CONFIG
    phases = zip(config["phase_names"], config["phase_labels"],
                 config["phase_colors"], strict=True)
    for phase, label, color in phases:
        points = [trial for trial in trials if trial["phase"] == phase]
        axis.scatter([t["kl"] for t in points], [t["keywords"] for t in points],
                     s=config["scatter_size"], color=color,
                     alpha=config["scatter_alpha"], label=label)
    _plot_pareto(axis, trials)
    for number, offset in zip(config["annotated_trials"],
                              config["annotation_offsets"], strict=True):
        trial = trials[number]
        axis.annotate(f"Trial {number}", (trial["kl"], trial["keywords"]),
                      xytext=offset, textcoords="offset points", fontsize=9,
                      arrowprops={"arrowstyle": "-", "lw": 0.65})


def _plot_pareto(axis, trials):
    config = PLOT_CONFIG
    points = [trial for trial in trials if trial["pareto"]]
    axis.scatter([t["kl"] for t in points], [t["keywords"] for t in points],
                 facecolors="none", edgecolors=config["pareto_color"],
                 s=config["pareto_size"], marker=config["pareto_marker"],
                 linewidth=0.9, label=f"Pareto candidates ({len(points)})")


def _render_figures(summary, staging):
    config = PLOT_CONFIG
    os.environ["MPLCONFIGDIR"] = str(staging / "matplotlib")
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as pyplot

    with pyplot.rc_context({"font.family": config["font_family"],
                            "font.size": config["font_size"]}):
        figure, axis = pyplot.subplots(figsize=config["figure_inches"],
                                       layout=config["layout"])
        _plot_candidates(axis, _read_plot_csv(render_csv(summary)))
        axis.axvline(config["gate_kl"], color=config["gate_color"], ls="--",
                     lw=1, label="Numerical gate boundaries")
        axis.axhline(config["gate_keywords"], color=config["gate_color"],
                     ls="--", lw=1)
        axis.set(xlim=config["xlim"], ylim=config["ylim"],
                 xlabel=config["xlabel"], ylabel=config["ylabel"])
        axis.grid(alpha=config["grid_alpha"])
        axis.legend(loc=config["legend_location"], fontsize=9, framealpha=0.95)
        artifacts = {}
        for name in FIGURE_OUTPUTS:
            path = staging / Path(name).name
            figure.savefig(path, dpi=config["dpi"])
            artifacts[name] = path.read_bytes()
        pyplot.close(figure)
        return artifacts


def _read_plot_csv(payload):
    rows = csv.DictReader(io.StringIO(payload.decode("utf-8")))
    return [{"trial_number": int(row["trial_number"]),
             "keywords": float(row["keywords"]), "kl": float(row["kl"]),
             "pareto": row["pareto"] == "true", "phase": row["phase"]}
            for row in rows]


def check_outputs(summary, paper_dir):
    """Check all derived bytes without writes/re-render; raise OutputError.

    Args:
        summary: Freshly recomputed RunSummary.
        paper_dir: Existing paper directory.
    Returns:
        None on success, including verified actual PDF/PNG hashes.
    Raises:
        OutputError: Derived text or figure inputs/bytes do not match.
    """
    paper_dir = Path(paper_dir).resolve()
    rendered = render_outputs(summary)
    try:
        for name, expected in rendered.items():
            if (paper_dir / name).read_bytes() != expected:
                raise OutputError(f"stale derived file: {name}")
        artifacts = {name: (paper_dir / name).read_bytes()
                     for name in FIGURE_OUTPUTS}
        actual = parse_json((paper_dir / MANIFEST).read_bytes(), MANIFEST)
        expected = _figure_manifest(paper_dir, rendered, artifacts)
        if actual != expected:
            raise OutputError("figure manifest/input/artifact hash mismatch")
    except (OSError, InputError) as error:
        raise OutputError(f"cannot verify artifacts: {error}") from error


def generate_outputs(summary, paper_dir):
    """Stage then atomically replace each artifact, writing manifest last.

    Args:
        summary: Fully validated RunSummary.
        paper_dir: Safe workspace-local destination.
    Returns:
        None; the final manifest binds every generated figure byte.
    Raises:
        OutputError: An artifact cannot be plotted or atomically replaced.
    """
    paper_dir = Path(paper_dir).resolve()
    build = paper_dir / "build"
    rendered = render_outputs(summary)
    try:
        build.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(prefix="evidence-", dir=build) as area:
            staging = Path(area)
            artifacts = _render_figures(summary, staging)
            manifest = _figure_manifest(paper_dir, rendered, artifacts)
            outputs = rendered | artifacts | {MANIFEST: json_bytes(manifest)}
            for index, (name, payload) in enumerate(outputs.items()):
                staged = staging / f"artifact-{index}"
                staged.write_bytes(payload)
                target = paper_dir / name
                target.parent.mkdir(parents=True, exist_ok=True)
                os.replace(staged, target)
    except (OSError, RuntimeError, ImportError) as error:
        raise OutputError(f"artifact generation failed: {error}") from error


def main(argv=None):
    """Execute the offline generation or check CLI.

    Args:
        argv: Argument list, or None to use process arguments.
    Returns:
        Status 0 on success, 2 for invalid input, 3 for stale/failed output.
    Raises:
        SystemExit: argparse rejects invalid command syntax.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--paper-dir", type=Path, default=DEFAULT_PAPER)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    try:
        source, paper = validate_paths(args.source, args.paper_dir)
        summary = load_summary(source)
    except InputError as error:
        print(f"INPUT ERROR: {error}", file=sys.stderr)
        return 2
    try:
        action = check_outputs if args.check else generate_outputs
        action(summary, paper)
    except OutputError as error:
        print(f"OUTPUT ERROR: {error}", file=sys.stderr)
        return 3
    verb = "Checked" if args.check else "Generated"
    print(f"{verb}: {summary['trial_count']} COMPLETE trials; "
          f"{summary['numerical_gate_count']} numerical gate passes; "
          f"acceptance={summary['acceptance_status']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
